server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094

external-server:
  matadata:
    url: http://localhost:8088

metadata:
  api:
    url: http://localhost:8088
