package com.fastcampus.kafkahandson.ugc.adapter.inspectedport;

import com.fastcampus.kafkahandson.ugc.CustomObjectMapper;
import com.fastcampus.kafkahandson.ugc.adapter.common.OperationType;
import com.fastcampus.kafkahandson.ugc.adapter.common.Topic;
import com.fastcampus.kafkahandson.ugc.adapter.originpost.OriginalPostMessage;
import com.fastcampus.kafkahandson.ugc.inspectedpost.InspectedPost;
import com.fastcampus.kafkahandson.ugc.port.InspectedPostMessageProducerPort;
import com.fastcampus.kafkahandson.ugc.post.model.Post;
import com.fasterxml.jackson.core.JsonProcessingException;
import lombok.RequiredArgsConstructor;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Component;

@RequiredArgsConstructor
@Component
public class InspectedPostMessageProduceAdapter implements InspectedPostMessageProducerPort {

	private final KafkaTemplate<String, String> kafkaTemplate;
	private static final CustomObjectMapper customObjectMapper = new CustomObjectMapper();

	@Override
	public void sendCreateMessage(InspectedPost post) {
		this.sendMessage(createSendMessage(post, OperationType.CREATE));
	}

	@Override
	public void sendUpdateMessage(InspectedPost post) {
		this.sendMessage(createSendMessage(post, OperationType.UPDATE));
	}

	@Override
	public void sendDeleteMessage(Long postId) {
		// InspectedPostMessage sendMessage = createSendMessage(post, OperationType.DELETE);
		InspectedPostMessage message = new InspectedPostMessage(
			postId,
			null,
			OperationType.DELETE
		);
		this.sendMessage(message);
	}

	private static InspectedPostMessage createSendMessage(InspectedPost post, OperationType type) {
		return new InspectedPostMessage(
			post.getPost().getId(),
			new InspectedPostMessage.Payload(
				post.getPost(),
				post.getCategoryName(),
				post.getAutoGeneratedTags(),
				post.getInspectedAt()
			),
			type
		);
	}

	private void sendMessage(InspectedPostMessage message) {
		try {
			kafkaTemplate.send(
				Topic.INSPECTED_POST,
				message.getId().toString(),
				customObjectMapper.writeValueAsString(message)
			);

		} catch (Exception ex) {
			throw new RuntimeException(ex);
		}
	}

	private OriginalPostMessage convertToMessage(Long id, Post post, OperationType operationType) {
		return new OriginalPostMessage(
			id,
			post == null ? null : new OriginalPostMessage.Payload(
				post.getId(),
				post.getTitle(),
				post.getContent(),
				post.getUserId(),
				post.getCategoryId(),
				post.getCreatedAt(),
				post.getUpdatedAt(),
				post.getDeletedAt()
			),
			operationType
		);
	}

	private void sendMessage(OriginalPostMessage message) {
		try {
			kafkaTemplate.send(
				Topic.ORIGINAL_POST,
				message.getId().toString(),
				customObjectMapper.writeValueAsString(message));
		} catch (JsonProcessingException e) {
			// TODO: log error
		}
	}
}
